// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamedata.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prefab int32

const (
	Prefab_Invalid      Prefab = 0
	Prefab_ClientPrefab Prefab = 1
	Prefab_DemoBox      Prefab = 2
)

var Prefab_name = map[int32]string{
	0: "Invalid",
	1: "ClientPrefab",
	2: "DemoBox",
}

var Prefab_value = map[string]int32{
	"Invalid":      0,
	"ClientPrefab": 1,
	"DemoBox":      2,
}

func (x Prefab) String() string {
	return proto.EnumName(Prefab_name, int32(x))
}

func (Prefab) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{0}
}

type Header_OpCode int32

const (
	Header_Invalid Header_OpCode = 0
	// simulation server establishes connection with game server
	Header_SimulationServerJoined Header_OpCode = 1
	// (A.1) client informs game server of successful connection to
	// coordinator
	Header_ClientJoined Header_OpCode = 100
	// (A.2) game server tells sim server to create new client owned game
	// object from prefab
	// (A.3) sim server tells game server of new client game object and id
	// (A.4) game server tells client to create new client owned game
	// object from prefab
	Header_NewClientGameObject Header_OpCode = 200
	// (B.1) sim server tells game server to create new game object from prefab
	// (B.2) game server tells clients to create new game object from prefab
	Header_NewGameObject Header_OpCode = 201
	// (A.5) (FixedUpdate) sim server sends existing client game object's delta to game server
	// (B.3) (FixedUpdate) game server sends existing game object's delta to all clients
	Header_GameObjectDelta Header_OpCode = 300
)

var Header_OpCode_name = map[int32]string{
	0:   "Invalid",
	1:   "SimulationServerJoined",
	100: "ClientJoined",
	200: "NewClientGameObject",
	201: "NewGameObject",
	300: "GameObjectDelta",
}

var Header_OpCode_value = map[string]int32{
	"Invalid":                0,
	"SimulationServerJoined": 1,
	"ClientJoined":           100,
	"NewClientGameObject":    200,
	"NewGameObject":          201,
	"GameObjectDelta":        300,
}

func (x Header_OpCode) String() string {
	return proto.EnumName(Header_OpCode_name, int32(x))
}

func (Header_OpCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{7, 0}
}

type Packet struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Packet) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type SimulationServerJoin struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimulationServerJoin) Reset()         { *m = SimulationServerJoin{} }
func (m *SimulationServerJoin) String() string { return proto.CompactTextString(m) }
func (*SimulationServerJoin) ProtoMessage()    {}
func (*SimulationServerJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{1}
}

func (m *SimulationServerJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulationServerJoin.Unmarshal(m, b)
}
func (m *SimulationServerJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulationServerJoin.Marshal(b, m, deterministic)
}
func (m *SimulationServerJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulationServerJoin.Merge(m, src)
}
func (m *SimulationServerJoin) XXX_Size() int {
	return xxx_messageInfo_SimulationServerJoin.Size(m)
}
func (m *SimulationServerJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulationServerJoin.DiscardUnknown(m)
}

var xxx_messageInfo_SimulationServerJoin proto.InternalMessageInfo

func (m *SimulationServerJoin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ClientJoined struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientJoined) Reset()         { *m = ClientJoined{} }
func (m *ClientJoined) String() string { return proto.CompactTextString(m) }
func (*ClientJoined) ProtoMessage()    {}
func (*ClientJoined) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{2}
}

func (m *ClientJoined) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientJoined.Unmarshal(m, b)
}
func (m *ClientJoined) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientJoined.Marshal(b, m, deterministic)
}
func (m *ClientJoined) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientJoined.Merge(m, src)
}
func (m *ClientJoined) XXX_Size() int {
	return xxx_messageInfo_ClientJoined.Size(m)
}
func (m *ClientJoined) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientJoined.DiscardUnknown(m)
}

var xxx_messageInfo_ClientJoined proto.InternalMessageInfo

func (m *ClientJoined) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NewClientGameObject struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Prefab               Prefab   `protobuf:"varint,2,opt,name=prefab,proto3,enum=main.Prefab" json:"prefab,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewClientGameObject) Reset()         { *m = NewClientGameObject{} }
func (m *NewClientGameObject) String() string { return proto.CompactTextString(m) }
func (*NewClientGameObject) ProtoMessage()    {}
func (*NewClientGameObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{3}
}

func (m *NewClientGameObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewClientGameObject.Unmarshal(m, b)
}
func (m *NewClientGameObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewClientGameObject.Marshal(b, m, deterministic)
}
func (m *NewClientGameObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewClientGameObject.Merge(m, src)
}
func (m *NewClientGameObject) XXX_Size() int {
	return xxx_messageInfo_NewClientGameObject.Size(m)
}
func (m *NewClientGameObject) XXX_DiscardUnknown() {
	xxx_messageInfo_NewClientGameObject.DiscardUnknown(m)
}

var xxx_messageInfo_NewClientGameObject proto.InternalMessageInfo

func (m *NewClientGameObject) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NewClientGameObject) GetPrefab() Prefab {
	if m != nil {
		return m.Prefab
	}
	return Prefab_Invalid
}

type NewGameObject struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Prefab               Prefab   `protobuf:"varint,2,opt,name=prefab,proto3,enum=main.Prefab" json:"prefab,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewGameObject) Reset()         { *m = NewGameObject{} }
func (m *NewGameObject) String() string { return proto.CompactTextString(m) }
func (*NewGameObject) ProtoMessage()    {}
func (*NewGameObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{4}
}

func (m *NewGameObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewGameObject.Unmarshal(m, b)
}
func (m *NewGameObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewGameObject.Marshal(b, m, deterministic)
}
func (m *NewGameObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewGameObject.Merge(m, src)
}
func (m *NewGameObject) XXX_Size() int {
	return xxx_messageInfo_NewGameObject.Size(m)
}
func (m *NewGameObject) XXX_DiscardUnknown() {
	xxx_messageInfo_NewGameObject.DiscardUnknown(m)
}

var xxx_messageInfo_NewGameObject proto.InternalMessageInfo

func (m *NewGameObject) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NewGameObject) GetPrefab() Prefab {
	if m != nil {
		return m.Prefab
	}
	return Prefab_Invalid
}

type GameObjectDelta struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position             *Vector2 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Vector2 `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameObjectDelta) Reset()         { *m = GameObjectDelta{} }
func (m *GameObjectDelta) String() string { return proto.CompactTextString(m) }
func (*GameObjectDelta) ProtoMessage()    {}
func (*GameObjectDelta) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{5}
}

func (m *GameObjectDelta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameObjectDelta.Unmarshal(m, b)
}
func (m *GameObjectDelta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameObjectDelta.Marshal(b, m, deterministic)
}
func (m *GameObjectDelta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameObjectDelta.Merge(m, src)
}
func (m *GameObjectDelta) XXX_Size() int {
	return xxx_messageInfo_GameObjectDelta.Size(m)
}
func (m *GameObjectDelta) XXX_DiscardUnknown() {
	xxx_messageInfo_GameObjectDelta.DiscardUnknown(m)
}

var xxx_messageInfo_GameObjectDelta proto.InternalMessageInfo

func (m *GameObjectDelta) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GameObjectDelta) GetPosition() *Vector2 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *GameObjectDelta) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

func (m *GameObjectDelta) GetVelocity() *Vector2 {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type Vector2 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2) Reset()         { *m = Vector2{} }
func (m *Vector2) String() string { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()    {}
func (*Vector2) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{6}
}

func (m *Vector2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2.Unmarshal(m, b)
}
func (m *Vector2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2.Marshal(b, m, deterministic)
}
func (m *Vector2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2.Merge(m, src)
}
func (m *Vector2) XXX_Size() int {
	return xxx_messageInfo_Vector2.Size(m)
}
func (m *Vector2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2 proto.InternalMessageInfo

func (m *Vector2) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector2) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Header struct {
	Cid int32 `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// connection is lost
	Timestamp            int32         `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OpCode               Header_OpCode `protobuf:"varint,3,opt,name=opCode,proto3,enum=main.Header_OpCode" json:"opCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{7}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *Header) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Header) GetOpCode() Header_OpCode {
	if m != nil {
		return m.OpCode
	}
	return Header_Invalid
}

func init() {
	proto.RegisterEnum("main.Prefab", Prefab_name, Prefab_value)
	proto.RegisterEnum("main.Header_OpCode", Header_OpCode_name, Header_OpCode_value)
	proto.RegisterType((*Packet)(nil), "main.Packet")
	proto.RegisterType((*SimulationServerJoin)(nil), "main.SimulationServerJoin")
	proto.RegisterType((*ClientJoined)(nil), "main.ClientJoined")
	proto.RegisterType((*NewClientGameObject)(nil), "main.NewClientGameObject")
	proto.RegisterType((*NewGameObject)(nil), "main.NewGameObject")
	proto.RegisterType((*GameObjectDelta)(nil), "main.GameObjectDelta")
	proto.RegisterType((*Vector2)(nil), "main.Vector2")
	proto.RegisterType((*Header)(nil), "main.Header")
}

func init() { proto.RegisterFile("gamedata.proto", fileDescriptor_38d51a89ffb18ac9) }

var fileDescriptor_38d51a89ffb18ac9 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0xc5, 0x59, 0x97, 0x8d, 0xdb, 0xae, 0x58, 0x77, 0x15, 0x0a, 0x15, 0x42, 0x53, 0x04, 0xa8,
	0x80, 0x94, 0x49, 0x85, 0x1f, 0x80, 0x15, 0x41, 0x41, 0xda, 0x26, 0x4f, 0x42, 0xbc, 0xba, 0xf1,
	0x5d, 0x31, 0x24, 0x71, 0x94, 0x79, 0x5d, 0xf3, 0x05, 0x7c, 0x00, 0xbf, 0xc1, 0x87, 0xc0, 0xd7,
	0xf0, 0x0b, 0xc8, 0x4e, 0xdb, 0x31, 0xda, 0xb7, 0xbd, 0xc5, 0xe7, 0x1c, 0x1f, 0x9f, 0xdc, 0x73,
	0xa1, 0x3b, 0x95, 0x39, 0x29, 0x69, 0x65, 0x52, 0x56, 0xc6, 0x1a, 0x6c, 0xe5, 0x52, 0x17, 0xfd,
	0x07, 0x53, 0x63, 0xa6, 0x19, 0x1d, 0x7a, 0x6c, 0x72, 0x79, 0x7e, 0x28, 0x8b, 0xba, 0x11, 0xc4,
	0x9f, 0x21, 0x3c, 0x95, 0xe9, 0x37, 0xb2, 0xf8, 0x18, 0xc2, 0x2f, 0x24, 0x15, 0x55, 0x11, 0x3b,
	0x60, 0x83, 0xf6, 0xb0, 0x93, 0xb8, 0xbb, 0xc9, 0x7b, 0x8f, 0x89, 0x05, 0x87, 0x03, 0x68, 0x39,
	0xfb, 0x68, 0xcb, 0x6b, 0x7a, 0x49, 0xe3, 0x9c, 0x2c, 0x9d, 0x93, 0xd7, 0x45, 0x2d, 0xbc, 0x22,
	0x7e, 0x0a, 0xbd, 0x33, 0x9d, 0x5f, 0x66, 0xd2, 0x6a, 0x53, 0x9c, 0x51, 0x35, 0xa3, 0xea, 0x83,
	0xd1, 0x05, 0x76, 0x21, 0xd0, 0xca, 0xbf, 0xb1, 0x2d, 0x02, 0xad, 0xe2, 0x47, 0xd0, 0x39, 0xca,
	0x34, 0x15, 0xd6, 0xb1, 0xa4, 0xd6, 0xf8, 0x8f, 0xb0, 0x7f, 0x4c, 0x57, 0x8d, 0xe4, 0x9d, 0xcc,
	0xe9, 0x64, 0xf2, 0x95, 0x52, 0xeb, 0x64, 0xe3, 0xd1, 0x52, 0x36, 0x1e, 0xb9, 0xf8, 0x65, 0x45,
	0xe7, 0x72, 0x12, 0x05, 0x07, 0x6c, 0xd0, 0x5d, 0xc6, 0x3f, 0xf5, 0x98, 0x58, 0x70, 0xf1, 0x5b,
	0xd8, 0x3b, 0xa6, 0xab, 0x5b, 0xdb, 0xfc, 0x60, 0x70, 0xef, 0xda, 0x64, 0x44, 0x99, 0x95, 0x6b,
	0x4e, 0xcf, 0x60, 0xb7, 0x34, 0x17, 0xda, 0xfd, 0xbd, 0xf7, 0x6a, 0x0f, 0xf7, 0x1a, 0xaf, 0x4f,
	0x94, 0x5a, 0x53, 0x0d, 0xc5, 0x8a, 0xc6, 0x3e, 0xec, 0x56, 0xc6, 0xfa, 0x41, 0xf9, 0xc1, 0x06,
	0x62, 0x75, 0x76, 0x36, 0x33, 0xca, 0x4c, 0xaa, 0x6d, 0x1d, 0xb5, 0x36, 0xda, 0x2c, 0xe9, 0xf8,
	0x09, 0xec, 0x2c, 0x40, 0xec, 0x00, 0x9b, 0xfb, 0x2c, 0x81, 0x60, 0x73, 0x77, 0xaa, 0x7d, 0x86,
	0x40, 0xb0, 0x3a, 0xfe, 0xc3, 0x20, 0x6c, 0x5a, 0x45, 0x0e, 0x5b, 0xe9, 0x6a, 0xd8, 0xee, 0x13,
	0x1f, 0xc2, 0x5d, 0xab, 0x73, 0xba, 0xb0, 0x32, 0x2f, 0xfd, 0x95, 0x6d, 0x71, 0x0d, 0xe0, 0x0b,
	0x08, 0x4d, 0x79, 0x64, 0x14, 0xf9, 0x98, 0xdd, 0xe1, 0xfe, 0xbf, 0x3b, 0x92, 0x9c, 0x78, 0x4a,
	0x2c, 0x24, 0xf1, 0x77, 0x06, 0x61, 0x03, 0x61, 0x1b, 0x76, 0xc6, 0xc5, 0x4c, 0x66, 0x5a, 0xf1,
	0x3b, 0xd8, 0x87, 0xfb, 0x9b, 0x16, 0x83, 0x14, 0x67, 0xc8, 0x6f, 0x2e, 0x03, 0x57, 0x18, 0x6d,
	0xac, 0x9f, 0xff, 0x62, 0x88, 0xff, 0x75, 0xc9, 0x7f, 0x33, 0xec, 0xad, 0xf5, 0xc2, 0x7f, 0x06,
	0xcf, 0x5f, 0x41, 0xd8, 0x14, 0x78, 0x33, 0xc8, 0xea, 0xb1, 0x86, 0xe4, 0xcc, 0xd1, 0x23, 0xca,
	0xcd, 0x1b, 0x33, 0xe7, 0xc1, 0x24, 0xf4, 0x4b, 0xfd, 0xf2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x02, 0xfd, 0xd3, 0x74, 0x54, 0x03, 0x00, 0x00,
}
