// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gamedata.proto

package gamedata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prefab int32

const (
	Prefab_Invalid Prefab = 0
	Prefab_DemoBox Prefab = 1
)

var Prefab_name = map[int32]string{
	0: "Invalid",
	1: "DemoBox",
}

var Prefab_value = map[string]int32{
	"Invalid": 0,
	"DemoBox": 1,
}

func (x Prefab) String() string {
	return proto.EnumName(Prefab_name, int32(x))
}

func (Prefab) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{0}
}

type Header_OpCode int32

const (
	Header_Invalid Header_OpCode = 0
	// (A.1) client informs game server of successful connection to
	// coordinator
	Header_ClientOnline      Header_OpCode = 100
	Header_GameServerOnline  Header_OpCode = 101
	Header_GameServerStart   Header_OpCode = 102
	Header_ClientGameRequest Header_OpCode = 200
	Header_ClientGameCancel  Header_OpCode = 201
	Header_ClientGameFound   Header_OpCode = 202
	// (A.5) (FixedUpdate) sim server sends existing client game object's delta to game server
	// (B.3) (FixedUpdate) game server sends existing game object's delta to all clients
	Header_GameObject Header_OpCode = 300
	Header_Rigidbody  Header_OpCode = 301
)

var Header_OpCode_name = map[int32]string{
	0:   "Invalid",
	100: "ClientOnline",
	101: "GameServerOnline",
	102: "GameServerStart",
	200: "ClientGameRequest",
	201: "ClientGameCancel",
	202: "ClientGameFound",
	300: "GameObject",
	301: "Rigidbody",
}

var Header_OpCode_value = map[string]int32{
	"Invalid":           0,
	"ClientOnline":      100,
	"GameServerOnline":  101,
	"GameServerStart":   102,
	"ClientGameRequest": 200,
	"ClientGameCancel":  201,
	"ClientGameFound":   202,
	"GameObject":        300,
	"Rigidbody":         301,
}

func (x Header_OpCode) String() string {
	return proto.EnumName(Header_OpCode_name, int32(x))
}

func (Header_OpCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{10, 0}
}

type Packet struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Packet) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type ClientOnline struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientOnline) Reset()         { *m = ClientOnline{} }
func (m *ClientOnline) String() string { return proto.CompactTextString(m) }
func (*ClientOnline) ProtoMessage()    {}
func (*ClientOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{1}
}

func (m *ClientOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientOnline.Unmarshal(m, b)
}
func (m *ClientOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientOnline.Marshal(b, m, deterministic)
}
func (m *ClientOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientOnline.Merge(m, src)
}
func (m *ClientOnline) XXX_Size() int {
	return xxx_messageInfo_ClientOnline.Size(m)
}
func (m *ClientOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientOnline.DiscardUnknown(m)
}

var xxx_messageInfo_ClientOnline proto.InternalMessageInfo

func (m *ClientOnline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GameServerOnline struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServerOnline) Reset()         { *m = GameServerOnline{} }
func (m *GameServerOnline) String() string { return proto.CompactTextString(m) }
func (*GameServerOnline) ProtoMessage()    {}
func (*GameServerOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{2}
}

func (m *GameServerOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerOnline.Unmarshal(m, b)
}
func (m *GameServerOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerOnline.Marshal(b, m, deterministic)
}
func (m *GameServerOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerOnline.Merge(m, src)
}
func (m *GameServerOnline) XXX_Size() int {
	return xxx_messageInfo_GameServerOnline.Size(m)
}
func (m *GameServerOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerOnline.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerOnline proto.InternalMessageInfo

func (m *GameServerOnline) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GameServerOnline) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GameServerOnline) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type GameServerStart struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Clients              []string `protobuf:"bytes,2,rep,name=clients,proto3" json:"clients,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServerStart) Reset()         { *m = GameServerStart{} }
func (m *GameServerStart) String() string { return proto.CompactTextString(m) }
func (*GameServerStart) ProtoMessage()    {}
func (*GameServerStart) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{3}
}

func (m *GameServerStart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerStart.Unmarshal(m, b)
}
func (m *GameServerStart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerStart.Marshal(b, m, deterministic)
}
func (m *GameServerStart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerStart.Merge(m, src)
}
func (m *GameServerStart) XXX_Size() int {
	return xxx_messageInfo_GameServerStart.Size(m)
}
func (m *GameServerStart) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerStart.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerStart proto.InternalMessageInfo

func (m *GameServerStart) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GameServerStart) GetClients() []string {
	if m != nil {
		return m.Clients
	}
	return nil
}

type ClientGameFound struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGameFound) Reset()         { *m = ClientGameFound{} }
func (m *ClientGameFound) String() string { return proto.CompactTextString(m) }
func (*ClientGameFound) ProtoMessage()    {}
func (*ClientGameFound) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{4}
}

func (m *ClientGameFound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGameFound.Unmarshal(m, b)
}
func (m *ClientGameFound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGameFound.Marshal(b, m, deterministic)
}
func (m *ClientGameFound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGameFound.Merge(m, src)
}
func (m *ClientGameFound) XXX_Size() int {
	return xxx_messageInfo_ClientGameFound.Size(m)
}
func (m *ClientGameFound) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGameFound.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGameFound proto.InternalMessageInfo

func (m *ClientGameFound) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ClientGameRequest struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGameRequest) Reset()         { *m = ClientGameRequest{} }
func (m *ClientGameRequest) String() string { return proto.CompactTextString(m) }
func (*ClientGameRequest) ProtoMessage()    {}
func (*ClientGameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{5}
}

func (m *ClientGameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGameRequest.Unmarshal(m, b)
}
func (m *ClientGameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGameRequest.Marshal(b, m, deterministic)
}
func (m *ClientGameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGameRequest.Merge(m, src)
}
func (m *ClientGameRequest) XXX_Size() int {
	return xxx_messageInfo_ClientGameRequest.Size(m)
}
func (m *ClientGameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGameRequest proto.InternalMessageInfo

func (m *ClientGameRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type ClientGameCancel struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientGameCancel) Reset()         { *m = ClientGameCancel{} }
func (m *ClientGameCancel) String() string { return proto.CompactTextString(m) }
func (*ClientGameCancel) ProtoMessage()    {}
func (*ClientGameCancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{6}
}

func (m *ClientGameCancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGameCancel.Unmarshal(m, b)
}
func (m *ClientGameCancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGameCancel.Marshal(b, m, deterministic)
}
func (m *ClientGameCancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGameCancel.Merge(m, src)
}
func (m *ClientGameCancel) XXX_Size() int {
	return xxx_messageInfo_ClientGameCancel.Size(m)
}
func (m *ClientGameCancel) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGameCancel.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGameCancel proto.InternalMessageInfo

type GameObject struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Prefab               Prefab   `protobuf:"varint,2,opt,name=Prefab,proto3,enum=gamedata.Prefab" json:"Prefab,omitempty"`
	Position             *Vector2 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameObject) Reset()         { *m = GameObject{} }
func (m *GameObject) String() string { return proto.CompactTextString(m) }
func (*GameObject) ProtoMessage()    {}
func (*GameObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{7}
}

func (m *GameObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameObject.Unmarshal(m, b)
}
func (m *GameObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameObject.Marshal(b, m, deterministic)
}
func (m *GameObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameObject.Merge(m, src)
}
func (m *GameObject) XXX_Size() int {
	return xxx_messageInfo_GameObject.Size(m)
}
func (m *GameObject) XXX_DiscardUnknown() {
	xxx_messageInfo_GameObject.DiscardUnknown(m)
}

var xxx_messageInfo_GameObject proto.InternalMessageInfo

func (m *GameObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GameObject) GetPrefab() Prefab {
	if m != nil {
		return m.Prefab
	}
	return Prefab_Invalid
}

func (m *GameObject) GetPosition() *Vector2 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *GameObject) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

type Rigidbody struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Prefab               Prefab   `protobuf:"varint,2,opt,name=Prefab,proto3,enum=gamedata.Prefab" json:"Prefab,omitempty"`
	Position             *Vector2 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Vector2 `protobuf:"bytes,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rigidbody) Reset()         { *m = Rigidbody{} }
func (m *Rigidbody) String() string { return proto.CompactTextString(m) }
func (*Rigidbody) ProtoMessage()    {}
func (*Rigidbody) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{8}
}

func (m *Rigidbody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rigidbody.Unmarshal(m, b)
}
func (m *Rigidbody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rigidbody.Marshal(b, m, deterministic)
}
func (m *Rigidbody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rigidbody.Merge(m, src)
}
func (m *Rigidbody) XXX_Size() int {
	return xxx_messageInfo_Rigidbody.Size(m)
}
func (m *Rigidbody) XXX_DiscardUnknown() {
	xxx_messageInfo_Rigidbody.DiscardUnknown(m)
}

var xxx_messageInfo_Rigidbody proto.InternalMessageInfo

func (m *Rigidbody) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Rigidbody) GetPrefab() Prefab {
	if m != nil {
		return m.Prefab
	}
	return Prefab_Invalid
}

func (m *Rigidbody) GetPosition() *Vector2 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Rigidbody) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

func (m *Rigidbody) GetVelocity() *Vector2 {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type Vector2 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2) Reset()         { *m = Vector2{} }
func (m *Vector2) String() string { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()    {}
func (*Vector2) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{9}
}

func (m *Vector2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2.Unmarshal(m, b)
}
func (m *Vector2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2.Marshal(b, m, deterministic)
}
func (m *Vector2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2.Merge(m, src)
}
func (m *Vector2) XXX_Size() int {
	return xxx_messageInfo_Vector2.Size(m)
}
func (m *Vector2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2 proto.InternalMessageInfo

func (m *Vector2) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector2) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Header struct {
	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// connection is lost
	OpCode               Header_OpCode `protobuf:"varint,2,opt,name=opCode,proto3,enum=gamedata.Header_OpCode" json:"opCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_38d51a89ffb18ac9, []int{10}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *Header) GetOpCode() Header_OpCode {
	if m != nil {
		return m.OpCode
	}
	return Header_Invalid
}

func init() {
	proto.RegisterEnum("gamedata.Prefab", Prefab_name, Prefab_value)
	proto.RegisterEnum("gamedata.Header_OpCode", Header_OpCode_name, Header_OpCode_value)
	proto.RegisterType((*Packet)(nil), "gamedata.Packet")
	proto.RegisterType((*ClientOnline)(nil), "gamedata.ClientOnline")
	proto.RegisterType((*GameServerOnline)(nil), "gamedata.GameServerOnline")
	proto.RegisterType((*GameServerStart)(nil), "gamedata.GameServerStart")
	proto.RegisterType((*ClientGameFound)(nil), "gamedata.ClientGameFound")
	proto.RegisterType((*ClientGameRequest)(nil), "gamedata.ClientGameRequest")
	proto.RegisterType((*ClientGameCancel)(nil), "gamedata.ClientGameCancel")
	proto.RegisterType((*GameObject)(nil), "gamedata.GameObject")
	proto.RegisterType((*Rigidbody)(nil), "gamedata.Rigidbody")
	proto.RegisterType((*Vector2)(nil), "gamedata.Vector2")
	proto.RegisterType((*Header)(nil), "gamedata.Header")
}

func init() { proto.RegisterFile("gamedata.proto", fileDescriptor_38d51a89ffb18ac9) }

var fileDescriptor_38d51a89ffb18ac9 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0x4f, 0x8f, 0x12, 0x4f,
	0x14, 0xfc, 0xf5, 0xc0, 0x0e, 0xf0, 0xd8, 0x40, 0xef, 0xfb, 0xe1, 0x8a, 0x7b, 0xc2, 0x4e, 0x4c,
	0x26, 0x1a, 0x87, 0x64, 0x3d, 0x7a, 0x52, 0x88, 0xca, 0x89, 0x4d, 0x6f, 0xe2, 0xc9, 0x98, 0x34,
	0x33, 0x0f, 0x1c, 0x1d, 0xa6, 0x71, 0x18, 0x08, 0xf3, 0x05, 0xbc, 0xfb, 0x3d, 0xf4, 0xee, 0xcd,
	0xab, 0xfa, 0xa9, 0xcc, 0xf4, 0x34, 0x7f, 0x76, 0xd1, 0xbb, 0xb7, 0xa9, 0xea, 0xa2, 0xba, 0x1e,
	0xaf, 0x1a, 0x5a, 0x33, 0x35, 0xa7, 0x50, 0x65, 0xca, 0x5f, 0xa4, 0x3a, 0xd3, 0x58, 0xdf, 0xe2,
	0x8b, 0x7b, 0x33, 0xad, 0x67, 0x31, 0xf5, 0x0d, 0x3f, 0x59, 0x4d, 0xfb, 0x2a, 0xc9, 0x4b, 0x91,
	0x78, 0x03, 0xee, 0x95, 0x0a, 0x3e, 0x50, 0x86, 0x1e, 0xb8, 0xef, 0x48, 0x85, 0x94, 0x76, 0x59,
	0x8f, 0x79, 0xcd, 0x4b, 0xee, 0xef, 0xfc, 0x5e, 0x19, 0x5e, 0xda, 0x73, 0xf4, 0xa0, 0x5a, 0xd0,
	0x5d, 0xc7, 0xe8, 0x3a, 0x7e, 0xe9, 0xee, 0x6f, 0xdd, 0xfd, 0x67, 0x49, 0x2e, 0x8d, 0x42, 0x08,
	0x38, 0x1d, 0xc4, 0x11, 0x25, 0xd9, 0x38, 0x89, 0xa3, 0x84, 0x10, 0xa1, 0x9a, 0xa8, 0x39, 0x99,
	0x1b, 0x1a, 0xd2, 0x7c, 0x8b, 0xb7, 0xc0, 0x5f, 0xaa, 0x39, 0x5d, 0x53, 0xba, 0xa6, 0xd4, 0xea,
	0xce, 0xc1, 0x5d, 0x52, 0x90, 0x52, 0x66, 0x95, 0x16, 0x15, 0x7c, 0x4a, 0xb3, 0x48, 0x27, 0xe6,
	0xee, 0x86, 0xb4, 0x08, 0x2f, 0xa0, 0x1e, 0xa8, 0x85, 0x0a, 0xa2, 0x2c, 0xef, 0x56, 0x7a, 0xcc,
	0x3b, 0x91, 0x3b, 0x2c, 0x9e, 0x42, 0x7b, 0xef, 0x7f, 0x9d, 0xa9, 0x34, 0xc3, 0x16, 0x38, 0xa3,
	0xa1, 0xb5, 0x76, 0x46, 0x43, 0xec, 0x42, 0x2d, 0x30, 0x31, 0x97, 0x5d, 0xa7, 0x57, 0xf1, 0x1a,
	0x72, 0x0b, 0xc5, 0x7d, 0x68, 0x97, 0x03, 0x14, 0x16, 0x2f, 0xf4, 0x2a, 0x09, 0x6f, 0xff, 0x58,
	0x3c, 0x82, 0xb3, 0xbd, 0x44, 0xd2, 0xc7, 0x15, 0x2d, 0x0f, 0x83, 0xb2, 0xc3, 0xa0, 0x02, 0x81,
	0xef, 0xc5, 0x03, 0x95, 0x04, 0x14, 0x8b, 0xcf, 0x0c, 0xa0, 0x80, 0xe3, 0xc9, 0x7b, 0x0a, 0x8e,
	0xc3, 0x79, 0xe0, 0x5e, 0xa5, 0x34, 0x55, 0x13, 0x33, 0x73, 0xeb, 0x70, 0x2f, 0x25, 0x2f, 0xed,
	0x39, 0x3e, 0x86, 0xfa, 0x42, 0x2f, 0xa3, 0xac, 0xb8, 0xb6, 0x62, 0x76, 0x73, 0xb6, 0xd7, 0xbe,
	0xa6, 0x20, 0xd3, 0xe9, 0xa5, 0xdc, 0x49, 0x8a, 0x3f, 0x2d, 0xd5, 0x99, 0x32, 0xf2, 0x6a, 0x8f,
	0x79, 0x8e, 0xdc, 0x61, 0xf1, 0x9d, 0x41, 0x43, 0x46, 0xb3, 0x28, 0x9c, 0xe8, 0x30, 0xff, 0x27,
	0x22, 0x15, 0x56, 0x6b, 0x8a, 0xb5, 0xd9, 0xf1, 0xc9, 0x5f, 0xad, 0xb6, 0x12, 0xf1, 0x00, 0x6a,
	0x96, 0xc4, 0x53, 0x60, 0x1b, 0x93, 0xde, 0x91, 0x6c, 0x53, 0xa0, 0xdc, 0xe4, 0x76, 0x24, 0xcb,
	0xc5, 0x27, 0x07, 0xdc, 0xb2, 0xde, 0xc8, 0xa1, 0x12, 0x44, 0xa1, 0x1d, 0xb3, 0xf8, 0xc4, 0x3e,
	0xb8, 0x7a, 0x31, 0xd0, 0x21, 0xd9, 0x39, 0xef, 0xde, 0x7e, 0x12, 0xfe, 0xd8, 0x1c, 0x4b, 0x2b,
	0x13, 0xdf, 0x18, 0xb8, 0x25, 0x85, 0x4d, 0xa8, 0x8d, 0x92, 0xb5, 0x8a, 0xa3, 0x90, 0xff, 0x87,
	0xfc, 0xe6, 0x3b, 0xe0, 0x21, 0x76, 0x8e, 0x5b, 0xcf, 0x09, 0xff, 0x3f, 0xea, 0x2a, 0x9f, 0xe2,
	0xf9, 0x1f, 0x0a, 0xc6, 0x7f, 0x30, 0xbc, 0x73, 0xdc, 0x25, 0xfe, 0x93, 0x61, 0xe7, 0xa8, 0xb2,
	0xfc, 0x17, 0xc3, 0xf6, 0x61, 0xc7, 0xf8, 0x17, 0x07, 0x5b, 0x07, 0x0b, 0xe6, 0x5f, 0x9d, 0x87,
	0x62, 0xbb, 0xd3, 0x9b, 0xc9, 0x9b, 0x50, 0x1b, 0xd2, 0x5c, 0x3f, 0xd7, 0x1b, 0xce, 0x26, 0xae,
	0x79, 0xe2, 0x4f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x2b, 0x24, 0xb3, 0x6a, 0x04, 0x00,
	0x00,
}
