// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serializable.proto

package serializable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet_OpCode int32

const (
	Packet_Invalid Packet_OpCode = 0
	// connection related
	Packet_ClientDisconnect Packet_OpCode = 100
	// game server related
	Packet_SeatConfiguration Packet_OpCode = 200
	Packet_Seat              Packet_OpCode = 201
	Packet_RunSimulation     Packet_OpCode = 202
)

var Packet_OpCode_name = map[int32]string{
	0:   "Invalid",
	100: "ClientDisconnect",
	200: "SeatConfiguration",
	201: "Seat",
	202: "RunSimulation",
}

var Packet_OpCode_value = map[string]int32{
	"Invalid":           0,
	"ClientDisconnect":  100,
	"SeatConfiguration": 200,
	"Seat":              201,
	"RunSimulation":     202,
}

func (x Packet_OpCode) String() string {
	return proto.EnumName(Packet_OpCode_name, int32(x))
}

func (Packet_OpCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{0, 0}
}

type Packet struct {
	OpCode               Packet_OpCode `protobuf:"varint,1,opt,name=opCode,proto3,enum=serializable.Packet_OpCode" json:"opCode,omitempty"`
	Data                 *any.Any      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetOpCode() Packet_OpCode {
	if m != nil {
		return m.OpCode
	}
	return Packet_Invalid
}

func (m *Packet) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type SeatConfiguration struct {
	Seats                []*Seat  `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeatConfiguration) Reset()         { *m = SeatConfiguration{} }
func (m *SeatConfiguration) String() string { return proto.CompactTextString(m) }
func (*SeatConfiguration) ProtoMessage()    {}
func (*SeatConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{1}
}

func (m *SeatConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeatConfiguration.Unmarshal(m, b)
}
func (m *SeatConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeatConfiguration.Marshal(b, m, deterministic)
}
func (m *SeatConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeatConfiguration.Merge(m, src)
}
func (m *SeatConfiguration) XXX_Size() int {
	return xxx_messageInfo_SeatConfiguration.Size(m)
}
func (m *SeatConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_SeatConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_SeatConfiguration proto.InternalMessageInfo

func (m *SeatConfiguration) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

type Context3D struct {
	Tick                 int32          `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Transforms           []*Transform   `protobuf:"bytes,2,rep,name=transforms,proto3" json:"transforms,omitempty"`
	RigidBodies          []*Rigidbody3D `protobuf:"bytes,3,rep,name=rigidBodies,proto3" json:"rigidBodies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Context3D) Reset()         { *m = Context3D{} }
func (m *Context3D) String() string { return proto.CompactTextString(m) }
func (*Context3D) ProtoMessage()    {}
func (*Context3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{2}
}

func (m *Context3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context3D.Unmarshal(m, b)
}
func (m *Context3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context3D.Marshal(b, m, deterministic)
}
func (m *Context3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context3D.Merge(m, src)
}
func (m *Context3D) XXX_Size() int {
	return xxx_messageInfo_Context3D.Size(m)
}
func (m *Context3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Context3D.DiscardUnknown(m)
}

var xxx_messageInfo_Context3D proto.InternalMessageInfo

func (m *Context3D) GetTick() int32 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *Context3D) GetTransforms() []*Transform {
	if m != nil {
		return m.Transforms
	}
	return nil
}

func (m *Context3D) GetRigidBodies() []*Rigidbody3D {
	if m != nil {
		return m.RigidBodies
	}
	return nil
}

type Context2D struct {
	Tick                 int32          `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Transforms           []*Transform   `protobuf:"bytes,2,rep,name=transforms,proto3" json:"transforms,omitempty"`
	RigidBodies          []*Rigidbody2D `protobuf:"bytes,3,rep,name=rigidBodies,proto3" json:"rigidBodies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Context2D) Reset()         { *m = Context2D{} }
func (m *Context2D) String() string { return proto.CompactTextString(m) }
func (*Context2D) ProtoMessage()    {}
func (*Context2D) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{3}
}

func (m *Context2D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context2D.Unmarshal(m, b)
}
func (m *Context2D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context2D.Marshal(b, m, deterministic)
}
func (m *Context2D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context2D.Merge(m, src)
}
func (m *Context2D) XXX_Size() int {
	return xxx_messageInfo_Context2D.Size(m)
}
func (m *Context2D) XXX_DiscardUnknown() {
	xxx_messageInfo_Context2D.DiscardUnknown(m)
}

var xxx_messageInfo_Context2D proto.InternalMessageInfo

func (m *Context2D) GetTick() int32 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *Context2D) GetTransforms() []*Transform {
	if m != nil {
		return m.Transforms
	}
	return nil
}

func (m *Context2D) GetRigidBodies() []*Rigidbody2D {
	if m != nil {
		return m.RigidBodies
	}
	return nil
}

type Transform struct {
	ID                   string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position             *Vector3    `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *Quaternion `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Transform) Reset()         { *m = Transform{} }
func (m *Transform) String() string { return proto.CompactTextString(m) }
func (*Transform) ProtoMessage()    {}
func (*Transform) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{4}
}

func (m *Transform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transform.Unmarshal(m, b)
}
func (m *Transform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transform.Marshal(b, m, deterministic)
}
func (m *Transform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transform.Merge(m, src)
}
func (m *Transform) XXX_Size() int {
	return xxx_messageInfo_Transform.Size(m)
}
func (m *Transform) XXX_DiscardUnknown() {
	xxx_messageInfo_Transform.DiscardUnknown(m)
}

var xxx_messageInfo_Transform proto.InternalMessageInfo

func (m *Transform) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Transform) GetPosition() *Vector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Transform) GetRotation() *Quaternion {
	if m != nil {
		return m.Rotation
	}
	return nil
}

type Rigidbody2D struct {
	ID                   string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position             *Vector2    `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *Quaternion `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Vector2    `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Rigidbody2D) Reset()         { *m = Rigidbody2D{} }
func (m *Rigidbody2D) String() string { return proto.CompactTextString(m) }
func (*Rigidbody2D) ProtoMessage()    {}
func (*Rigidbody2D) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{5}
}

func (m *Rigidbody2D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rigidbody2D.Unmarshal(m, b)
}
func (m *Rigidbody2D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rigidbody2D.Marshal(b, m, deterministic)
}
func (m *Rigidbody2D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rigidbody2D.Merge(m, src)
}
func (m *Rigidbody2D) XXX_Size() int {
	return xxx_messageInfo_Rigidbody2D.Size(m)
}
func (m *Rigidbody2D) XXX_DiscardUnknown() {
	xxx_messageInfo_Rigidbody2D.DiscardUnknown(m)
}

var xxx_messageInfo_Rigidbody2D proto.InternalMessageInfo

func (m *Rigidbody2D) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Rigidbody2D) GetPosition() *Vector2 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Rigidbody2D) GetRotation() *Quaternion {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Rigidbody2D) GetVelocity() *Vector2 {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type Rigidbody3D struct {
	ID                   string      `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position             *Vector3    `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             *Quaternion `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Vector3    `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Rigidbody3D) Reset()         { *m = Rigidbody3D{} }
func (m *Rigidbody3D) String() string { return proto.CompactTextString(m) }
func (*Rigidbody3D) ProtoMessage()    {}
func (*Rigidbody3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{6}
}

func (m *Rigidbody3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rigidbody3D.Unmarshal(m, b)
}
func (m *Rigidbody3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rigidbody3D.Marshal(b, m, deterministic)
}
func (m *Rigidbody3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rigidbody3D.Merge(m, src)
}
func (m *Rigidbody3D) XXX_Size() int {
	return xxx_messageInfo_Rigidbody3D.Size(m)
}
func (m *Rigidbody3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Rigidbody3D.DiscardUnknown(m)
}

var xxx_messageInfo_Rigidbody3D proto.InternalMessageInfo

func (m *Rigidbody3D) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Rigidbody3D) GetPosition() *Vector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Rigidbody3D) GetRotation() *Quaternion {
	if m != nil {
		return m.Rotation
	}
	return nil
}

func (m *Rigidbody3D) GetVelocity() *Vector3 {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type Vector2 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2) Reset()         { *m = Vector2{} }
func (m *Vector2) String() string { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()    {}
func (*Vector2) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{7}
}

func (m *Vector2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2.Unmarshal(m, b)
}
func (m *Vector2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2.Marshal(b, m, deterministic)
}
func (m *Vector2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2.Merge(m, src)
}
func (m *Vector2) XXX_Size() int {
	return xxx_messageInfo_Vector2.Size(m)
}
func (m *Vector2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2 proto.InternalMessageInfo

func (m *Vector2) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector2) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Vector3 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector3) Reset()         { *m = Vector3{} }
func (m *Vector3) String() string { return proto.CompactTextString(m) }
func (*Vector3) ProtoMessage()    {}
func (*Vector3) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{8}
}

func (m *Vector3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector3.Unmarshal(m, b)
}
func (m *Vector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector3.Marshal(b, m, deterministic)
}
func (m *Vector3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector3.Merge(m, src)
}
func (m *Vector3) XXX_Size() int {
	return xxx_messageInfo_Vector3.Size(m)
}
func (m *Vector3) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector3.DiscardUnknown(m)
}

var xxx_messageInfo_Vector3 proto.InternalMessageInfo

func (m *Vector3) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector3) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector3) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Quaternion struct {
	W                    float32  `protobuf:"fixed32,1,opt,name=w,proto3" json:"w,omitempty"`
	X                    float32  `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quaternion) Reset()         { *m = Quaternion{} }
func (m *Quaternion) String() string { return proto.CompactTextString(m) }
func (*Quaternion) ProtoMessage()    {}
func (*Quaternion) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{9}
}

func (m *Quaternion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quaternion.Unmarshal(m, b)
}
func (m *Quaternion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quaternion.Marshal(b, m, deterministic)
}
func (m *Quaternion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quaternion.Merge(m, src)
}
func (m *Quaternion) XXX_Size() int {
	return xxx_messageInfo_Quaternion.Size(m)
}
func (m *Quaternion) XXX_DiscardUnknown() {
	xxx_messageInfo_Quaternion.DiscardUnknown(m)
}

var xxx_messageInfo_Quaternion proto.InternalMessageInfo

func (m *Quaternion) GetW() float32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *Quaternion) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Quaternion) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Quaternion) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Seat struct {
	Owner                int32    `protobuf:"varint,1,opt,name=owner,proto3" json:"owner,omitempty"`
	GUID                 string   `protobuf:"bytes,2,opt,name=GUID,proto3" json:"GUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}
func (*Seat) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{10}
}

func (m *Seat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Seat.Unmarshal(m, b)
}
func (m *Seat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Seat.Marshal(b, m, deterministic)
}
func (m *Seat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Seat.Merge(m, src)
}
func (m *Seat) XXX_Size() int {
	return xxx_messageInfo_Seat.Size(m)
}
func (m *Seat) XXX_DiscardUnknown() {
	xxx_messageInfo_Seat.DiscardUnknown(m)
}

var xxx_messageInfo_Seat proto.InternalMessageInfo

func (m *Seat) GetOwner() int32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *Seat) GetGUID() string {
	if m != nil {
		return m.GUID
	}
	return ""
}

func init() {
	proto.RegisterEnum("serializable.Packet_OpCode", Packet_OpCode_name, Packet_OpCode_value)
	proto.RegisterType((*Packet)(nil), "serializable.Packet")
	proto.RegisterType((*SeatConfiguration)(nil), "serializable.SeatConfiguration")
	proto.RegisterType((*Context3D)(nil), "serializable.Context3D")
	proto.RegisterType((*Context2D)(nil), "serializable.Context2D")
	proto.RegisterType((*Transform)(nil), "serializable.Transform")
	proto.RegisterType((*Rigidbody2D)(nil), "serializable.Rigidbody2D")
	proto.RegisterType((*Rigidbody3D)(nil), "serializable.Rigidbody3D")
	proto.RegisterType((*Vector2)(nil), "serializable.Vector2")
	proto.RegisterType((*Vector3)(nil), "serializable.Vector3")
	proto.RegisterType((*Quaternion)(nil), "serializable.Quaternion")
	proto.RegisterType((*Seat)(nil), "serializable.Seat")
}

func init() { proto.RegisterFile("serializable.proto", fileDescriptor_cd0c84d25a72589c) }

var fileDescriptor_cd0c84d25a72589c = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x71, 0xda, 0x75, 0xeb, 0xdb, 0x31, 0x95, 0x57, 0x05, 0x32, 0xb8, 0x54, 0x91, 0x90,
	0x7a, 0xca, 0x20, 0x41, 0xe2, 0x80, 0x38, 0x40, 0x23, 0xa1, 0x9e, 0x00, 0x0f, 0xb8, 0xbb, 0x89,
	0x5b, 0x59, 0xcb, 0xec, 0xca, 0x71, 0xd6, 0xa6, 0x67, 0xbe, 0x02, 0x1f, 0x86, 0x6f, 0xc0, 0x9f,
	0x2f, 0x85, 0xe2, 0x34, 0x25, 0x41, 0x68, 0x42, 0x70, 0xd8, 0x2d, 0xf6, 0xfb, 0x7b, 0x9e, 0xf7,
	0xb1, 0x1d, 0x1b, 0x30, 0xe3, 0x5a, 0xb0, 0x54, 0x6c, 0xd9, 0x3c, 0xe5, 0xfe, 0x4a, 0x2b, 0xa3,
	0xf0, 0xb8, 0x39, 0xf7, 0xe0, 0x74, 0xa9, 0xd4, 0x32, 0xe5, 0x67, 0xb6, 0x36, 0xcf, 0x17, 0x67,
	0x4c, 0x16, 0x15, 0xe8, 0xfd, 0x20, 0xd0, 0x7b, 0xcb, 0xe2, 0x0b, 0x6e, 0x30, 0x84, 0x9e, 0x5a,
	0x4d, 0x55, 0xc2, 0x5d, 0x32, 0x26, 0x93, 0x93, 0xe0, 0xa1, 0xdf, 0x32, 0xae, 0x28, 0xff, 0x8d,
	0x45, 0xe8, 0x0e, 0xc5, 0x09, 0x74, 0x13, 0x66, 0x98, 0xeb, 0x8c, 0xc9, 0x64, 0x10, 0x8c, 0xfc,
	0xaa, 0x93, 0x5f, 0x77, 0xf2, 0x5f, 0xca, 0x82, 0x5a, 0xc2, 0x9b, 0x43, 0xaf, 0xd2, 0xe2, 0x00,
	0x0e, 0x67, 0xf2, 0x8a, 0xa5, 0x22, 0x19, 0xde, 0xc2, 0x11, 0x0c, 0xa7, 0xa9, 0xe0, 0xd2, 0x44,
	0x22, 0x8b, 0x95, 0x94, 0x3c, 0x36, 0xc3, 0x04, 0xef, 0xc1, 0x9d, 0x73, 0xce, 0xcc, 0x54, 0xc9,
	0x85, 0x58, 0xe6, 0x9a, 0x19, 0xa1, 0xe4, 0xf0, 0x2b, 0xc1, 0x3e, 0x74, 0xcb, 0xf9, 0xe1, 0x37,
	0x82, 0x08, 0xb7, 0x69, 0x2e, 0xcf, 0xc5, 0x65, 0x9e, 0x56, 0xe5, 0xef, 0xc4, 0x7b, 0xf1, 0x07,
	0x19, 0x4e, 0xe0, 0x20, 0xe3, 0xcc, 0x64, 0x2e, 0x19, 0x77, 0x26, 0x83, 0x00, 0xdb, 0xcb, 0x2a,
	0x79, 0x5a, 0x01, 0xde, 0x67, 0x02, 0xfd, 0xa9, 0x92, 0x86, 0x6f, 0x4c, 0x18, 0x21, 0x42, 0xd7,
	0x88, 0xf8, 0xc2, 0xee, 0xc6, 0x01, 0xb5, 0xdf, 0xf8, 0x0c, 0xc0, 0x68, 0x26, 0xb3, 0x85, 0xd2,
	0x97, 0x99, 0xeb, 0x58, 0xc3, 0xfb, 0x6d, 0xc3, 0xf7, 0x75, 0x9d, 0x36, 0x50, 0x7c, 0x0e, 0x03,
	0x2d, 0x96, 0x22, 0x79, 0xa5, 0x12, 0xc1, 0x33, 0xb7, 0x63, 0x95, 0xa7, 0x6d, 0x25, 0x2d, 0x81,
	0xb9, 0x4a, 0x8a, 0x30, 0xa2, 0x4d, 0xba, 0x99, 0x2b, 0xb8, 0xc9, 0x5c, 0xc1, 0x6f, 0xb9, 0x3e,
	0x11, 0xe8, 0xef, 0x6d, 0xf1, 0x04, 0x9c, 0x59, 0x64, 0x53, 0xf5, 0xa9, 0x33, 0x8b, 0xf0, 0x09,
	0x1c, 0xad, 0x54, 0x26, 0xca, 0x33, 0xd8, 0xfd, 0x1e, 0x77, 0xdb, 0xbe, 0x1f, 0x79, 0x6c, 0x94,
	0x0e, 0xe9, 0x1e, 0xc3, 0xa7, 0x70, 0xa4, 0x95, 0xb1, 0xc7, 0xe6, 0x76, 0xac, 0xc4, 0x6d, 0x4b,
	0xde, 0xe5, 0xcc, 0x70, 0x2d, 0x85, 0x92, 0x74, 0x4f, 0x7a, 0x5f, 0x08, 0x0c, 0x1a, 0x19, 0xff,
	0x35, 0x48, 0xf0, 0xbf, 0x41, 0xca, 0x46, 0x57, 0x3c, 0x55, 0xb1, 0x30, 0x85, 0xdb, 0xbd, 0xb6,
	0x51, 0x8d, 0xb5, 0xb3, 0x87, 0xd1, 0x8d, 0x6d, 0xe2, 0xdf, 0x66, 0x0f, 0x1b, 0xd9, 0x1f, 0xc1,
	0xe1, 0x6e, 0x41, 0x78, 0x0c, 0x64, 0x63, 0x53, 0x3b, 0x94, 0x6c, 0xca, 0x51, 0x61, 0xd3, 0x3a,
	0x94, 0x14, 0x5e, 0x58, 0x63, 0xe1, 0x75, 0x58, 0x39, 0xda, 0xda, 0xbc, 0x0e, 0x25, 0x5b, 0x2f,
	0x02, 0xf8, 0x15, 0xb3, 0xac, 0xad, 0x6b, 0xdd, 0xba, 0x72, 0x71, 0x5a, 0x2e, 0x9d, 0x96, 0x4b,
	0xb7, 0x76, 0x79, 0x5c, 0x3d, 0x17, 0x38, 0x82, 0x03, 0xb5, 0x96, 0x5c, 0xef, 0xee, 0x4c, 0x35,
	0x28, 0x2f, 0xd2, 0xeb, 0x0f, 0xb3, 0xc8, 0x5a, 0xf5, 0xa9, 0xfd, 0x9e, 0xf7, 0xec, 0xcb, 0x15,
	0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x77, 0xb4, 0x0d, 0x55, 0x05, 0x00, 0x00,
}
