// Code generated by protoc-gen-go. DO NOT EDIT.
// source: serializable.proto

package serializable

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Prefab int32

const (
	Prefab_Invalid Prefab = 0
	Prefab_DemoBox Prefab = 1
)

var Prefab_name = map[int32]string{
	0: "Invalid",
	1: "DemoBox",
}

var Prefab_value = map[string]int32{
	"Invalid": 0,
	"DemoBox": 1,
}

func (x Prefab) String() string {
	return proto.EnumName(Prefab_name, int32(x))
}

func (Prefab) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{0}
}

type Force_ForceMode int32

const (
	Force_Force   Force_ForceMode = 0
	Force_Impulse Force_ForceMode = 1
)

var Force_ForceMode_name = map[int32]string{
	0: "Force",
	1: "Impulse",
}

var Force_ForceMode_value = map[string]int32{
	"Force":   0,
	"Impulse": 1,
}

func (x Force_ForceMode) String() string {
	return proto.EnumName(Force_ForceMode_name, int32(x))
}

func (Force_ForceMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{11, 0}
}

// this is a connection id that expires once the coordinator connection is
// lost
type Header_OpCode int32

const (
	Header_Invalid Header_OpCode = 0
	// Bi-directionally inform a connection closure
	Header_ClientDisconnect Header_OpCode = 100
	// Connection is established, not client asks to be accepted
	Header_ClientAppeal Header_OpCode = 101
	// Server trusts client, so inform client
	Header_ClientTrust           Header_OpCode = 102
	Header_ClientDatagramAddress Header_OpCode = 104
	// Partial seat packet sent to simulation, complete packet sent in
	// return to ALL player clients
	Header_ClientSeat Header_OpCode = 103
	// Current context of simulated objects at a certain time
	Header_Context Header_OpCode = 200
	// Object creation
	Header_GameObject Header_OpCode = 300
	Header_Rigidbody  Header_OpCode = 301
	// Object updates
	Header_Position Header_OpCode = 400
	Header_Rotation Header_OpCode = 401
	Header_Scale    Header_OpCode = 402
	Header_Velocity Header_OpCode = 403
	Header_Force    Header_OpCode = 404
)

var Header_OpCode_name = map[int32]string{
	0:   "Invalid",
	100: "ClientDisconnect",
	101: "ClientAppeal",
	102: "ClientTrust",
	104: "ClientDatagramAddress",
	103: "ClientSeat",
	200: "Context",
	300: "GameObject",
	301: "Rigidbody",
	400: "Position",
	401: "Rotation",
	402: "Scale",
	403: "Velocity",
	404: "Force",
}

var Header_OpCode_value = map[string]int32{
	"Invalid":               0,
	"ClientDisconnect":      100,
	"ClientAppeal":          101,
	"ClientTrust":           102,
	"ClientDatagramAddress": 104,
	"ClientSeat":            103,
	"Context":               200,
	"GameObject":            300,
	"Rigidbody":             301,
	"Position":              400,
	"Rotation":              401,
	"Scale":                 402,
	"Velocity":              403,
	"Force":                 404,
}

func (x Header_OpCode) String() string {
	return proto.EnumName(Header_OpCode_name, int32(x))
}

func (Header_OpCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{14, 0}
}

type Context3D struct {
	Tick                 int32          `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Transforms           []*Transform   `protobuf:"bytes,2,rep,name=transforms,proto3" json:"transforms,omitempty"`
	RigidBodies          []*Rigidbody3D `protobuf:"bytes,3,rep,name=rigidBodies,proto3" json:"rigidBodies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Context3D) Reset()         { *m = Context3D{} }
func (m *Context3D) String() string { return proto.CompactTextString(m) }
func (*Context3D) ProtoMessage()    {}
func (*Context3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{0}
}

func (m *Context3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context3D.Unmarshal(m, b)
}
func (m *Context3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context3D.Marshal(b, m, deterministic)
}
func (m *Context3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context3D.Merge(m, src)
}
func (m *Context3D) XXX_Size() int {
	return xxx_messageInfo_Context3D.Size(m)
}
func (m *Context3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Context3D.DiscardUnknown(m)
}

var xxx_messageInfo_Context3D proto.InternalMessageInfo

func (m *Context3D) GetTick() int32 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *Context3D) GetTransforms() []*Transform {
	if m != nil {
		return m.Transforms
	}
	return nil
}

func (m *Context3D) GetRigidBodies() []*Rigidbody3D {
	if m != nil {
		return m.RigidBodies
	}
	return nil
}

type Context2D struct {
	Tick                 int32          `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Transforms           []*Transform   `protobuf:"bytes,2,rep,name=transforms,proto3" json:"transforms,omitempty"`
	RigidBodies          []*Rigidbody2D `protobuf:"bytes,3,rep,name=rigidBodies,proto3" json:"rigidBodies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Context2D) Reset()         { *m = Context2D{} }
func (m *Context2D) String() string { return proto.CompactTextString(m) }
func (*Context2D) ProtoMessage()    {}
func (*Context2D) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{1}
}

func (m *Context2D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context2D.Unmarshal(m, b)
}
func (m *Context2D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context2D.Marshal(b, m, deterministic)
}
func (m *Context2D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context2D.Merge(m, src)
}
func (m *Context2D) XXX_Size() int {
	return xxx_messageInfo_Context2D.Size(m)
}
func (m *Context2D) XXX_DiscardUnknown() {
	xxx_messageInfo_Context2D.DiscardUnknown(m)
}

var xxx_messageInfo_Context2D proto.InternalMessageInfo

func (m *Context2D) GetTick() int32 {
	if m != nil {
		return m.Tick
	}
	return 0
}

func (m *Context2D) GetTransforms() []*Transform {
	if m != nil {
		return m.Transforms
	}
	return nil
}

func (m *Context2D) GetRigidBodies() []*Rigidbody2D {
	if m != nil {
		return m.RigidBodies
	}
	return nil
}

type Transform struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position             *Vector3 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transform) Reset()         { *m = Transform{} }
func (m *Transform) String() string { return proto.CompactTextString(m) }
func (*Transform) ProtoMessage()    {}
func (*Transform) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{2}
}

func (m *Transform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transform.Unmarshal(m, b)
}
func (m *Transform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transform.Marshal(b, m, deterministic)
}
func (m *Transform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transform.Merge(m, src)
}
func (m *Transform) XXX_Size() int {
	return xxx_messageInfo_Transform.Size(m)
}
func (m *Transform) XXX_DiscardUnknown() {
	xxx_messageInfo_Transform.DiscardUnknown(m)
}

var xxx_messageInfo_Transform proto.InternalMessageInfo

func (m *Transform) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Transform) GetPosition() *Vector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Transform) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

type Rigidbody2D struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position             *Vector2 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Vector2 `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rigidbody2D) Reset()         { *m = Rigidbody2D{} }
func (m *Rigidbody2D) String() string { return proto.CompactTextString(m) }
func (*Rigidbody2D) ProtoMessage()    {}
func (*Rigidbody2D) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{3}
}

func (m *Rigidbody2D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rigidbody2D.Unmarshal(m, b)
}
func (m *Rigidbody2D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rigidbody2D.Marshal(b, m, deterministic)
}
func (m *Rigidbody2D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rigidbody2D.Merge(m, src)
}
func (m *Rigidbody2D) XXX_Size() int {
	return xxx_messageInfo_Rigidbody2D.Size(m)
}
func (m *Rigidbody2D) XXX_DiscardUnknown() {
	xxx_messageInfo_Rigidbody2D.DiscardUnknown(m)
}

var xxx_messageInfo_Rigidbody2D proto.InternalMessageInfo

func (m *Rigidbody2D) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Rigidbody2D) GetPosition() *Vector2 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Rigidbody2D) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

func (m *Rigidbody2D) GetVelocity() *Vector2 {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type Rigidbody3D struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Position             *Vector3 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Velocity             *Vector3 `protobuf:"bytes,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rigidbody3D) Reset()         { *m = Rigidbody3D{} }
func (m *Rigidbody3D) String() string { return proto.CompactTextString(m) }
func (*Rigidbody3D) ProtoMessage()    {}
func (*Rigidbody3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{4}
}

func (m *Rigidbody3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rigidbody3D.Unmarshal(m, b)
}
func (m *Rigidbody3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rigidbody3D.Marshal(b, m, deterministic)
}
func (m *Rigidbody3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rigidbody3D.Merge(m, src)
}
func (m *Rigidbody3D) XXX_Size() int {
	return xxx_messageInfo_Rigidbody3D.Size(m)
}
func (m *Rigidbody3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Rigidbody3D.DiscardUnknown(m)
}

var xxx_messageInfo_Rigidbody3D proto.InternalMessageInfo

func (m *Rigidbody3D) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Rigidbody3D) GetPosition() *Vector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Rigidbody3D) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

func (m *Rigidbody3D) GetVelocity() *Vector3 {
	if m != nil {
		return m.Velocity
	}
	return nil
}

type OldPacket struct {
	OpCode               Header_OpCode `protobuf:"varint,1,opt,name=opCode,proto3,enum=serializable.Header_OpCode" json:"opCode,omitempty"`
	Data                 *any.Any      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Cid                  string        `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OldPacket) Reset()         { *m = OldPacket{} }
func (m *OldPacket) String() string { return proto.CompactTextString(m) }
func (*OldPacket) ProtoMessage()    {}
func (*OldPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{5}
}

func (m *OldPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OldPacket.Unmarshal(m, b)
}
func (m *OldPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OldPacket.Marshal(b, m, deterministic)
}
func (m *OldPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OldPacket.Merge(m, src)
}
func (m *OldPacket) XXX_Size() int {
	return xxx_messageInfo_OldPacket.Size(m)
}
func (m *OldPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_OldPacket.DiscardUnknown(m)
}

var xxx_messageInfo_OldPacket proto.InternalMessageInfo

func (m *OldPacket) GetOpCode() Header_OpCode {
	if m != nil {
		return m.OpCode
	}
	return Header_Invalid
}

func (m *OldPacket) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OldPacket) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type ClientSeat struct {
	// CID of client that is assigned to this seat
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// GUID of the object this seat is on
	Guid                 string   `protobuf:"bytes,2,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSeat) Reset()         { *m = ClientSeat{} }
func (m *ClientSeat) String() string { return proto.CompactTextString(m) }
func (*ClientSeat) ProtoMessage()    {}
func (*ClientSeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{6}
}

func (m *ClientSeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSeat.Unmarshal(m, b)
}
func (m *ClientSeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSeat.Marshal(b, m, deterministic)
}
func (m *ClientSeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSeat.Merge(m, src)
}
func (m *ClientSeat) XXX_Size() int {
	return xxx_messageInfo_ClientSeat.Size(m)
}
func (m *ClientSeat) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSeat.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSeat proto.InternalMessageInfo

func (m *ClientSeat) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ClientSeat) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type GameServerOnline struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Region               string   `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Capacity             int32    `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServerOnline) Reset()         { *m = GameServerOnline{} }
func (m *GameServerOnline) String() string { return proto.CompactTextString(m) }
func (*GameServerOnline) ProtoMessage()    {}
func (*GameServerOnline) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{7}
}

func (m *GameServerOnline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServerOnline.Unmarshal(m, b)
}
func (m *GameServerOnline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServerOnline.Marshal(b, m, deterministic)
}
func (m *GameServerOnline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServerOnline.Merge(m, src)
}
func (m *GameServerOnline) XXX_Size() int {
	return xxx_messageInfo_GameServerOnline.Size(m)
}
func (m *GameServerOnline) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServerOnline.DiscardUnknown(m)
}

var xxx_messageInfo_GameServerOnline proto.InternalMessageInfo

func (m *GameServerOnline) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *GameServerOnline) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *GameServerOnline) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type GameObject struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Prefab               Prefab   `protobuf:"varint,2,opt,name=Prefab,proto3,enum=serializable.Prefab" json:"Prefab,omitempty"`
	Position             *Vector2 `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Rotation             float32  `protobuf:"fixed32,4,opt,name=rotation,proto3" json:"rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameObject) Reset()         { *m = GameObject{} }
func (m *GameObject) String() string { return proto.CompactTextString(m) }
func (*GameObject) ProtoMessage()    {}
func (*GameObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{8}
}

func (m *GameObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameObject.Unmarshal(m, b)
}
func (m *GameObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameObject.Marshal(b, m, deterministic)
}
func (m *GameObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameObject.Merge(m, src)
}
func (m *GameObject) XXX_Size() int {
	return xxx_messageInfo_GameObject.Size(m)
}
func (m *GameObject) XXX_DiscardUnknown() {
	xxx_messageInfo_GameObject.DiscardUnknown(m)
}

var xxx_messageInfo_GameObject proto.InternalMessageInfo

func (m *GameObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GameObject) GetPrefab() Prefab {
	if m != nil {
		return m.Prefab
	}
	return Prefab_Invalid
}

func (m *GameObject) GetPosition() *Vector2 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *GameObject) GetRotation() float32 {
	if m != nil {
		return m.Rotation
	}
	return 0
}

type Velocity struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	X                    float32  `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Velocity) Reset()         { *m = Velocity{} }
func (m *Velocity) String() string { return proto.CompactTextString(m) }
func (*Velocity) ProtoMessage()    {}
func (*Velocity) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{9}
}

func (m *Velocity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Velocity.Unmarshal(m, b)
}
func (m *Velocity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Velocity.Marshal(b, m, deterministic)
}
func (m *Velocity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Velocity.Merge(m, src)
}
func (m *Velocity) XXX_Size() int {
	return xxx_messageInfo_Velocity.Size(m)
}
func (m *Velocity) XXX_DiscardUnknown() {
	xxx_messageInfo_Velocity.DiscardUnknown(m)
}

var xxx_messageInfo_Velocity proto.InternalMessageInfo

func (m *Velocity) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Velocity) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Velocity) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Position struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	X                    float32  `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{10}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Position) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Position) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Force struct {
	ID                   string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	X                    float32         `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32         `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	ForceMode            Force_ForceMode `protobuf:"varint,4,opt,name=forceMode,proto3,enum=serializable.Force_ForceMode" json:"forceMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Force) Reset()         { *m = Force{} }
func (m *Force) String() string { return proto.CompactTextString(m) }
func (*Force) ProtoMessage()    {}
func (*Force) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{11}
}

func (m *Force) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Force.Unmarshal(m, b)
}
func (m *Force) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Force.Marshal(b, m, deterministic)
}
func (m *Force) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Force.Merge(m, src)
}
func (m *Force) XXX_Size() int {
	return xxx_messageInfo_Force.Size(m)
}
func (m *Force) XXX_DiscardUnknown() {
	xxx_messageInfo_Force.DiscardUnknown(m)
}

var xxx_messageInfo_Force proto.InternalMessageInfo

func (m *Force) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Force) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Force) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Force) GetForceMode() Force_ForceMode {
	if m != nil {
		return m.ForceMode
	}
	return Force_Force
}

type Vector2 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector2) Reset()         { *m = Vector2{} }
func (m *Vector2) String() string { return proto.CompactTextString(m) }
func (*Vector2) ProtoMessage()    {}
func (*Vector2) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{12}
}

func (m *Vector2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector2.Unmarshal(m, b)
}
func (m *Vector2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector2.Marshal(b, m, deterministic)
}
func (m *Vector2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector2.Merge(m, src)
}
func (m *Vector2) XXX_Size() int {
	return xxx_messageInfo_Vector2.Size(m)
}
func (m *Vector2) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector2.DiscardUnknown(m)
}

var xxx_messageInfo_Vector2 proto.InternalMessageInfo

func (m *Vector2) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector2) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Vector3 struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector3) Reset()         { *m = Vector3{} }
func (m *Vector3) String() string { return proto.CompactTextString(m) }
func (*Vector3) ProtoMessage()    {}
func (*Vector3) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{13}
}

func (m *Vector3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector3.Unmarshal(m, b)
}
func (m *Vector3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector3.Marshal(b, m, deterministic)
}
func (m *Vector3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector3.Merge(m, src)
}
func (m *Vector3) XXX_Size() int {
	return xxx_messageInfo_Vector3.Size(m)
}
func (m *Vector3) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector3.DiscardUnknown(m)
}

var xxx_messageInfo_Vector3 proto.InternalMessageInfo

func (m *Vector3) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector3) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector3) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Header struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd0c84d25a72589c, []int{14}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("serializable.Prefab", Prefab_name, Prefab_value)
	proto.RegisterEnum("serializable.Force_ForceMode", Force_ForceMode_name, Force_ForceMode_value)
	proto.RegisterEnum("serializable.Header_OpCode", Header_OpCode_name, Header_OpCode_value)
	proto.RegisterType((*Context3D)(nil), "serializable.Context3D")
	proto.RegisterType((*Context2D)(nil), "serializable.Context2D")
	proto.RegisterType((*Transform)(nil), "serializable.Transform")
	proto.RegisterType((*Rigidbody2D)(nil), "serializable.Rigidbody2D")
	proto.RegisterType((*Rigidbody3D)(nil), "serializable.Rigidbody3D")
	proto.RegisterType((*OldPacket)(nil), "serializable.OldPacket")
	proto.RegisterType((*ClientSeat)(nil), "serializable.ClientSeat")
	proto.RegisterType((*GameServerOnline)(nil), "serializable.GameServerOnline")
	proto.RegisterType((*GameObject)(nil), "serializable.GameObject")
	proto.RegisterType((*Velocity)(nil), "serializable.Velocity")
	proto.RegisterType((*Position)(nil), "serializable.Position")
	proto.RegisterType((*Force)(nil), "serializable.Force")
	proto.RegisterType((*Vector2)(nil), "serializable.Vector2")
	proto.RegisterType((*Vector3)(nil), "serializable.Vector3")
	proto.RegisterType((*Header)(nil), "serializable.Header")
}

func init() { proto.RegisterFile("serializable.proto", fileDescriptor_cd0c84d25a72589c) }

var fileDescriptor_cd0c84d25a72589c = []byte{
	// 748 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xcd, 0x6a, 0xdb, 0x4a,
	0x14, 0xce, 0x48, 0xfe, 0x89, 0x8e, 0x7d, 0x9d, 0x61, 0x70, 0xee, 0x75, 0x72, 0xb9, 0x60, 0x74,
	0x29, 0x98, 0x52, 0x1c, 0x6a, 0x41, 0xba, 0xc8, 0x2a, 0x89, 0x69, 0x9b, 0x45, 0x71, 0x98, 0x84,
	0x2c, 0x0b, 0x63, 0x69, 0xec, 0x2a, 0x91, 0x35, 0x66, 0x34, 0x4e, 0xed, 0xd0, 0x87, 0xe8, 0x5f,
	0x16, 0x5d, 0xf5, 0x05, 0xda, 0xf7, 0xe8, 0xcb, 0x74, 0xdf, 0x65, 0xd1, 0x48, 0x72, 0xa4, 0x04,
	0x42, 0x52, 0x28, 0xdd, 0x98, 0x39, 0x73, 0xbe, 0xef, 0x9c, 0xcf, 0x67, 0xbe, 0x23, 0x20, 0x11,
	0x97, 0x3e, 0x0b, 0xfc, 0x0b, 0x36, 0x0c, 0x78, 0x77, 0x2a, 0x85, 0x12, 0xa4, 0x9e, 0xbf, 0xdb,
	0xdc, 0x18, 0x0b, 0x31, 0x0e, 0xf8, 0x96, 0xce, 0x0d, 0x67, 0xa3, 0x2d, 0x16, 0x2e, 0x12, 0xa0,
	0x7d, 0x89, 0xc0, 0xda, 0x17, 0xa1, 0xe2, 0x73, 0xe5, 0xf4, 0x09, 0x81, 0x92, 0xf2, 0xdd, 0xb3,
	0x16, 0x6a, 0xa3, 0x4e, 0x99, 0xea, 0x33, 0x79, 0x02, 0xa0, 0x24, 0x0b, 0xa3, 0x91, 0x90, 0x93,
	0xa8, 0x65, 0xb4, 0xcd, 0x4e, 0xad, 0xf7, 0x4f, 0xb7, 0xd0, 0xf3, 0x38, 0xcb, 0xd3, 0x1c, 0x94,
	0xec, 0x40, 0x4d, 0xfa, 0x63, 0xdf, 0xdb, 0x13, 0x9e, 0xcf, 0xa3, 0x96, 0xa9, 0x99, 0x1b, 0x45,
	0x26, 0x8d, 0x01, 0x43, 0xe1, 0x2d, 0x9c, 0x3e, 0xcd, 0xa3, 0xf3, 0xba, 0x7a, 0x7f, 0x52, 0x57,
	0xef, 0x9a, 0xae, 0x53, 0xb0, 0x96, 0x55, 0x49, 0x03, 0x8c, 0x83, 0xbe, 0x16, 0x65, 0x51, 0xe3,
	0xa0, 0x4f, 0x1e, 0xc3, 0xea, 0x54, 0x44, 0xbe, 0xf2, 0x45, 0xd8, 0x32, 0xda, 0xa8, 0x53, 0xeb,
	0xad, 0x17, 0xcb, 0x9e, 0x70, 0x57, 0x09, 0xe9, 0xd0, 0x25, 0x8c, 0x6c, 0xc2, 0xaa, 0x14, 0x8a,
	0x69, 0x8a, 0xd9, 0x46, 0x1d, 0x83, 0x2e, 0x63, 0xfb, 0x33, 0x82, 0x5a, 0x4e, 0xc8, 0xaf, 0xb6,
	0xeb, 0xdd, 0xad, 0x5d, 0x5c, 0xee, 0x9c, 0x07, 0xc2, 0xf5, 0xd5, 0xa2, 0x55, 0xba, 0xb5, 0x5c,
	0x06, 0x2b, 0x2a, 0x74, 0xfa, 0xbf, 0x79, 0x20, 0x77, 0x55, 0xe8, 0xe4, 0x14, 0xbe, 0x01, 0x6b,
	0x10, 0x78, 0x87, 0xcc, 0x3d, 0xe3, 0x8a, 0x38, 0x50, 0x11, 0xd3, 0x7d, 0xe1, 0x71, 0x2d, 0xb1,
	0xd1, 0xfb, 0xb7, 0xc8, 0x7e, 0xce, 0x99, 0xc7, 0x65, 0x77, 0xa0, 0x21, 0x34, 0x85, 0x92, 0x0e,
	0x94, 0x3c, 0xa6, 0x58, 0xaa, 0xbf, 0xd9, 0x4d, 0x76, 0xa9, 0x9b, 0xed, 0x52, 0x77, 0x37, 0x5c,
	0x50, 0x8d, 0x20, 0x18, 0x4c, 0xd7, 0xf7, 0xb4, 0x6a, 0x8b, 0xc6, 0x47, 0x7b, 0x1b, 0x60, 0x3f,
	0xf0, 0x79, 0xa8, 0x8e, 0x38, 0x53, 0xa4, 0x09, 0x65, 0xf1, 0x3a, 0xe4, 0x32, 0x1d, 0x50, 0x12,
	0xc4, 0xde, 0x1e, 0xcf, 0x7c, 0x4f, 0xd7, 0xb7, 0xa8, 0x3e, 0xdb, 0x2f, 0x01, 0x3f, 0x63, 0x13,
	0x7e, 0xc4, 0xe5, 0x39, 0x97, 0x83, 0x30, 0xf0, 0x43, 0x4e, 0xfe, 0x86, 0x4a, 0xc4, 0x5d, 0xc9,
	0x55, 0x4a, 0x4f, 0xa3, 0xf8, 0x5e, 0xf2, 0x71, 0x36, 0x61, 0x8b, 0xa6, 0x51, 0x3c, 0x48, 0x97,
	0x4d, 0x99, 0x1e, 0x96, 0xa9, 0xf7, 0x66, 0x19, 0xdb, 0x9f, 0x10, 0x40, 0xdc, 0x60, 0x30, 0x3c,
	0xe5, 0xae, 0xba, 0xf1, 0x6c, 0x8f, 0xa0, 0x72, 0x28, 0xf9, 0x88, 0x0d, 0x75, 0xc9, 0x46, 0xaf,
	0x59, 0x9c, 0x53, 0x92, 0xa3, 0x29, 0xa6, 0xf0, 0xc8, 0xe6, 0xfd, 0x6d, 0x58, 0xba, 0xe6, 0xfa,
	0x6d, 0x58, 0x3d, 0x49, 0x5f, 0xef, 0x86, 0xb0, 0x3a, 0xa0, 0xb9, 0xd6, 0x64, 0x50, 0x34, 0x8f,
	0xa3, 0x45, 0xea, 0x11, 0xb4, 0x88, 0x79, 0x87, 0x59, 0xfd, 0xfb, 0xf0, 0x2e, 0x11, 0x94, 0x9f,
	0x0a, 0xe9, 0xf2, 0xfb, 0xb0, 0xc8, 0x0e, 0x58, 0xa3, 0x98, 0xf4, 0x22, 0x76, 0x53, 0x49, 0x4f,
	0xe9, 0xbf, 0xe2, 0xbf, 0xd6, 0x35, 0x93, 0xdf, 0x18, 0x44, 0xaf, 0xf0, 0xf6, 0xff, 0x60, 0x2d,
	0xef, 0x89, 0x95, 0xb6, 0xc7, 0x2b, 0xa4, 0x06, 0xd5, 0x83, 0xc9, 0x74, 0x16, 0x44, 0x1c, 0x23,
	0xfb, 0x01, 0x54, 0xd3, 0xc1, 0x25, 0x42, 0x50, 0x41, 0x88, 0x91, 0xc9, 0x77, 0x32, 0x98, 0x73,
	0x1b, 0x2c, 0x8e, 0x2e, 0x32, 0xf5, 0x17, 0xf6, 0x0f, 0x04, 0x95, 0xc4, 0xed, 0xf6, 0x77, 0x04,
	0x95, 0xc4, 0xf1, 0xba, 0x7d, 0x78, 0xce, 0x02, 0xdf, 0xc3, 0x2b, 0xa4, 0x09, 0x38, 0xb1, 0x6e,
	0xdf, 0x8f, 0x5c, 0x11, 0x86, 0xdc, 0x55, 0xd8, 0x23, 0x18, 0xea, 0xc9, 0xed, 0xee, 0x74, 0xca,
	0x59, 0x80, 0x39, 0x59, 0x83, 0x5a, 0x72, 0x73, 0x2c, 0x67, 0x91, 0xc2, 0x23, 0xb2, 0x01, 0xeb,
	0x29, 0x91, 0x29, 0x36, 0x96, 0x6c, 0xb2, 0xeb, 0x79, 0x92, 0x47, 0x11, 0x7e, 0x45, 0x1a, 0xf9,
	0x75, 0xc0, 0x63, 0x52, 0x87, 0x6a, 0xfa, 0x8d, 0xc7, 0xdf, 0x10, 0x59, 0xcb, 0x7b, 0x12, 0x7f,
	0x31, 0x48, 0x03, 0xac, 0xe5, 0xc7, 0x05, 0x7f, 0x35, 0xc8, 0x5f, 0x57, 0x2f, 0x8c, 0xdf, 0x9a,
	0x71, 0x48, 0x53, 0xd3, 0xe0, 0x77, 0x26, 0x01, 0x28, 0x1f, 0xb9, 0x2c, 0xe0, 0xf8, 0xbd, 0x4e,
	0x65, 0x1e, 0xc2, 0x1f, 0x74, 0x2a, 0x19, 0xf1, 0x47, 0xf3, 0xa1, 0x9d, 0x79, 0xbb, 0xf8, 0x77,
	0x6b, 0x50, 0xed, 0xf3, 0x89, 0xd8, 0x13, 0x73, 0x8c, 0x86, 0x15, 0xbd, 0xdc, 0xce, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe8, 0x2d, 0x32, 0x7d, 0x5a, 0x07, 0x00, 0x00,
}
